-- MySQL Script generated by MySQL Workbench
-- Mon Feb 12 11:33:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`mentors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mentors` (
  `mentor_id` INT NOT NULL,
  `mentor_name` VARCHAR(45) NOT NULL,
  `email_id` VARCHAR(45) NULL,
  `contact_no` INT NOT NULL,
  `skill_set` VARCHAR(45) NULL,
  `experience` FLOAT NOT NULL,
  `mentor_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`mentor_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Company_Drive`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Company_Drive` (
  `Company_Name` INT NOT NULL,
  `Drive_Date` DATETIME NULL,
  `Skills` VARCHAR(45) NULL,
  `Offer_release_Cnt` VARCHAR(45) NULL,
  `Company_Drive_Cnt` INT NULL,
  `Student_Attended` INT NULL,
  `Student_id` INT NULL,
  PRIMARY KEY (`Company_Name`),
  INDEX `fk_Company_Drive_users1_idx` (`Student_id` ASC) VISIBLE,
  CONSTRAINT `fk_Company_Drive_users1`
    FOREIGN KEY (`Student_id`)
    REFERENCES `mydb`.`users` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `student_id` INT NOT NULL,
  `contact_no` INT NULL,
  `student_name` VARCHAR(45) NOT NULL,
  `email_id` VARCHAR(45) NOT NULL,
  `course_name` VARCHAR(20) NOT NULL,
  `mentor_id` INT NULL,
  `Batch_Name` VARCHAR(45) NOT NULL,
  `company_name` VARCHAR(45) NULL,
  `Offer_released` VARCHAR(5) NOT NULL,
  `Offer_released_Date` DATETIME NULL,
  PRIMARY KEY (`student_id`, `Batch_Name`),
  INDEX `fk_users_mentors1_idx` (`mentor_id` ASC) VISIBLE,
  INDEX `fk_users_Company_Drive1_idx` (`company_name` ASC) VISIBLE,
  CONSTRAINT `fk_users_mentors1`
    FOREIGN KEY (`mentor_id`)
    REFERENCES `mydb`.`mentors` (`mentor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_Company_Drive1`
    FOREIGN KEY (`company_name`)
    REFERENCES `mydb`.`Company_Drive` (`Company_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`codekata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`codekata` (
  `Concept_name` VARCHAR(30) NOT NULL,
  `Total_Questions` INT NOT NULL,
  `Status` VARCHAR(45) NULL DEFAULT 'Not Started',
  `Earned_Coins` INT NULL,
  `Solved_Count` INT NULL,
  `Student_id` INT NULL,
  PRIMARY KEY (`Concept_name`),
  INDEX `fk_codekata_users1_idx` (`Student_id` ASC) VISIBLE,
  CONSTRAINT `fk_codekata_users1`
    FOREIGN KEY (`Student_id`)
    REFERENCES `mydb`.`users` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`topics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`topics` (
  `Topics` VARCHAR(60) NOT NULL,
  `contents` VARCHAR(200) NULL,
  `Date` DATETIME NOT NULL,
  `Duration` INT NOT NULL,
  PRIMARY KEY (`Topics`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`attendance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`attendance` (
  `Student_id` INT NOT NULL,
  `Topics` VARCHAR(45) NOT NULL,
  `Date` DATETIME NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `Day_Count` INT NULL,
  INDEX `fk_attendance_users1_idx` (`Student_id` ASC) VISIBLE,
  INDEX `fk_attendance_topics1_idx` (`Topics` ASC) VISIBLE,
  CONSTRAINT `fk_attendance_users1`
    FOREIGN KEY (`Student_id`)
    REFERENCES `mydb`.`users` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_attendance_topics1`
    FOREIGN KEY (`Topics`)
    REFERENCES `mydb`.`topics` (`Topics`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_attendance_users2`
    FOREIGN KEY (`Student_id`)
    REFERENCES `mydb`.`users` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tasks` (
  `Topics` VARCHAR(60) NOT NULL,
  `Student_id` INT NOT NULL,
  `Batch_Name` VARCHAR(45) NULL,
  `Submitted_On` DATETIME NULL,
  `Score` DECIMAL(2) NULL,
  INDEX `fk_tasks_users1_idx` (`Student_id` ASC) VISIBLE,
  INDEX `fk_tasks_users2_idx` (`Batch_Name` ASC) VISIBLE,
  INDEX `fk_tasks_topics1_idx` (`Topics` ASC) VISIBLE,
  CONSTRAINT `fk_tasks_users1`
    FOREIGN KEY (`Student_id`)
    REFERENCES `mydb`.`users` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tasks_users2`
    FOREIGN KEY (`Batch_Name`)
    REFERENCES `mydb`.`users` (`Batch_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tasks_topics1`
    FOREIGN KEY (`Topics`)
    REFERENCES `mydb`.`topics` (`Topics`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
